import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';

export default [
  js.configs.recommended,
  {
    files: ['src/**/*.{js,jsx}'],
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-empty': ['error', { allowEmptyCatch: true }],
      'react-hooks/set-state-in-effect': 'off',
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        fetch: 'readonly',
        confirm: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        AbortController: 'readonly',
        location: 'readonly',
        navigator: 'readonly',
        Notification: 'readonly',
        CustomEvent: 'readonly',
        history: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        MediaRecorder: 'readonly',
        Blob: 'readonly',
        crypto: 'readonly',
        FileReader: 'readonly',
        speechSynthesis: 'readonly',
        Audio: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        URLSearchParams: 'readonly',
        WebSocket: 'readonly',
        sessionStorage: 'readonly',
      },
    },
  },
  { ignores: ['dist-build', 'node_modules', 'archive', '.vite-cache*', 'api'] },
];
